(library
 (public_name abduction)
 (name abduction)
 (wrapped true)
 (libraries core zutils zutils.prop CoverageType.language CoverageType.auxtyping CoverageType.preprocess CoverageType.typechecker_config CoverageType.typing CoverageType.statistic)
 (modules abductionConfig feature fvec_tab cegis templates infer_prop termsyn iteminfer)
 (preprocess (pps ppx_optcomp ppx_compare ppx_sexp_conv ppx_inline_test ppx_assert ppx_deriving.show ppx_deriving.eq ppx_deriving.ord ppx_deriving_yojson ppx_here)))
